# Workflow to test docker builds and publish to GitHub Container Registry when committing to master
name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3
        name: Checkout Repo
        with:
          fetch-depth: "0"
      
      - name: Generate Image Name
        id: name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Get Short SHA Of Last Commit
        id: short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get Long SHA Of Last Commit
        id: long
        run: echo "::set-output name=sha_long::$(git rev-parse HEAD)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.name.outputs.lowercase }}:${{ steps.short.outputs.sha_short }}
            ghcr.io/${{ steps.name.outputs.lowercase }}:${{ steps.long.outputs.sha_long }}