# Workflow to publish to GitHub Container Registry when committing to master
name: CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3
        name: Checkout Repo
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zozman/redirect-url
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.tag.outputs.new_tag }}
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}